# Generated by Django 5.0.3 on 2024-04-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_remove_recipe_images_image_recipe_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='is_optional',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='food_app.recipe'),
        ),
    ]
